export const SCORING = {
  VIP_BONUS: 30,
  VIP_HOUR_BONUS: 25,
  GROUP_PENALTY: 12,
  LOYALTY_WEIGHT: 0.8,
  WAITING_WEIGHT: 0.2,
  TICKET_WEIGHT: 0.05,
  RUSH_HOUR_WAITING_WEIGHT: 0.4,
  RECENT_UPGRADE_PENALTY: 10,
} as const;
